-- UK BMW aftermarket catalogue expansion
-- Engines: N54 · N55 · B58 · S55 · S58
-- Prices: realistic UK street GBP (£) as of 2025–2026 ballpark
-- Run after sql/schema.sql
--
-- Live app also mirrors these SKUs in src/data/mods/ukMarketSeed.ts

INSERT INTO parts (
  id,
  name,
  brand,
  category,
  price_gbp,
  description,
  claim,
  hp_gain,
  torque_nm_gain,
  figures_source,
  uk_mot_status,
  prerequisite_sku,
  compatible_tags,
  conflict_group,
  audio_revs_url,
  audio_flyby_url
) VALUES
-- ═══════════════════════════════════════════════════════════════
-- 1. ECU & TCU TUNING
-- ═══════════════════════════════════════════════════════════════
(
  'uk-bm3-stage1-license',
  'Stage 1 OTS License',
  'bootmod3',
  'ecu',
  495.00,
  'bootmod3 Stage 1 OTS flash license for BMW turbos — pump-fuel street maps via OBD. Includes monitor and map switching.',
  'OTS Stage 1 street maps',
  55,
  75,
  'tuner',
  'MOT Compliant',
  NULL,
  ARRAY['n54', 'n55', 's55', 'b58', 's58'],
  'ecu-tune',
  NULL,
  NULL
),
(
  'uk-bm3-stage2-license',
  'Stage 2 OTS License',
  'bootmod3',
  'ecu',
  495.00,
  'bootmod3 Stage 2 OTS license — requires a high-flow / sports downpipe. UK street calibrations for N54/N55/B58/S55/S58.',
  'OTS Stage 2 with DP',
  95,
  120,
  'tuner',
  'MOT Compliant',
  'High-Flow / Sports Downpipe',
  ARRAY['n54', 'n55', 's55', 'b58', 's58'],
  'ecu-tune',
  NULL,
  NULL
),
(
  'uk-mhd-super-license',
  'Flasher Super License',
  'MHD',
  'ecu',
  420.00,
  'MHD Super License — flasher, custom flash, monitor, and full OTS map packs for supported BMW ECUs. Adapter sold separately.',
  'All maps, one license',
  55,
  75,
  'tuner',
  'MOT Compliant',
  NULL,
  ARRAY['n54', 'n55', 's55', 'b58', 's58'],
  'ecu-tune',
  NULL,
  NULL
),
(
  'uk-mhd-wireless-obd',
  'Wireless OBD Adapter',
  'MHD',
  'ecu',
  75.00,
  'Official MHD WiFi OBD adapter for flashing and logging from iOS/Android. Required for wireless MHD on most cars.',
  'Flash without a cable',
  0,
  NULL,
  'oem',
  'MOT Compliant',
  NULL,
  ARRAY['n54', 'n55', 's55', 'b58', 's58'],
  'obd-adapter',
  NULL,
  NULL
),
(
  'uk-xhp-zf8-flasher',
  'ZF8 Transmission Flasher',
  'xHP',
  'drivetrain',
  285.00,
  'xHP flash for ZF 8HP automatics — sharper shifts, raised slip limits, launch control options. No crank horsepower gain.',
  'Gearbox wake-up',
  0,
  NULL,
  'tuner',
  'MOT Compliant',
  NULL,
  ARRAY['n54', 'n55', 's55', 'b58', 's58'],
  'tcu-flash',
  NULL,
  NULL
),
(
  'uk-femto-dme-unlock-g',
  'DME Unlock Service (G-Series)',
  'FEMTO',
  'ecu',
  850.00,
  'FEMTO bench unlock for locked G-series / post-2020 BMW DMEs so MHD or bootmod3 can flash. Unlock labour only — no map included.',
  'Unlock locked G-series DMEs',
  0,
  NULL,
  'tuner',
  'MOT Compliant',
  NULL,
  ARRAY['b58', 's58'],
  NULL,
  NULL,
  NULL
),

-- ═══════════════════════════════════════════════════════════════
-- 2. INTAKES & CHARGEPIPES
-- ═══════════════════════════════════════════════════════════════
(
  'uk-eventuri-carbon-intake',
  'Gloss Carbon Intake System',
  'Eventuri',
  'intake',
  1150.00,
  'Eventuri sealed gloss carbon intake — OEM+ fitment with measured flow gains on B58/S58/S55/N55/N54 platforms.',
  'Sealed carbon intake',
  15,
  18,
  'tuner',
  'MOT Compliant',
  NULL,
  ARRAY['n54', 'n55', 's55', 'b58', 's58'],
  'intake-system',
  NULL,
  NULL
),
(
  'uk-mst-cai',
  'Performance Cold Air Intake',
  'MST Performance',
  'intake',
  385.00,
  'MST cold-air intake — popular UK Stage 1 bolt-on with stronger induction sound and filter area.',
  'Induction roar',
  12,
  15,
  'tuner',
  'MOT Compliant',
  NULL,
  ARRAY['n54', 'n55', 's55', 'b58', 's58'],
  'intake-system',
  NULL,
  NULL
),
(
  'uk-forge-induction-kit',
  'Induction Kit',
  'Forge Motorsport',
  'intake',
  310.00,
  'Forge Motorsport open-cone induction kit — UK-made hard pipe and high-flow filter for turbo BMWs.',
  'UK-made induction kit',
  10,
  12,
  'tuner',
  'MOT Compliant',
  NULL,
  ARRAY['n54', 'n55', 's55', 'b58', 's58'],
  'intake-system',
  NULL,
  NULL
),
(
  'uk-ftp-chargepipe',
  'Aluminum Chargepipe Kit',
  'FTP',
  'intake',
  245.00,
  'FTP aluminium chargepipe kit — replaces brittle OEM plastic, supports boost upgrades and meth bungs where fitted.',
  'No more cracked OEM pipes',
  0,
  NULL,
  'estimated',
  'MOT Compliant',
  NULL,
  ARRAY['n54', 'n55', 's55', 'b58', 's58'],
  'chargepipe',
  NULL,
  NULL
),
(
  'uk-bms-dual-cone-b58',
  'B58 Dual Cone Intake',
  'Burger Motorsports',
  'intake',
  220.00,
  'BMS dual-cone intake for B58 — simple drop-in, strong induction note, Stage 1 friendly.',
  'Dual-cone Stage 1 staple',
  8,
  10,
  'tuner',
  'MOT Compliant',
  NULL,
  ARRAY['b58'],
  'intake-system',
  NULL,
  NULL
),

-- ═══════════════════════════════════════════════════════════════
-- 3. EXHAUSTS & DOWNPIPES
-- ═══════════════════════════════════════════════════════════════
(
  'uk-vrsf-4-catless-dp',
  '4" Catless Downpipe',
  'VRSF',
  'exhaust',
  320.00,
  'VRSF 4" catless downpipe — maximum flow for Stage 2+. Not MOT-legal for UK road use.',
  'Max flow, track only',
  25,
  35,
  'tuner',
  'Track / Off-Road Only',
  NULL,
  ARRAY['n54', 'n55', 's55', 'b58', 's58'],
  'downpipe',
  '/audio/b58-vrsf-dp-revs.mp3',
  '/audio/b58-vrsf-dp-flyby.mp3'
),
(
  'uk-mad-200cel-sports-dp',
  '200-CEL High Flow Catted Downpipe',
  'MAD',
  'exhaust',
  690.00,
  'MAD 200-CEL high-flow sports-cat downpipe — UK-friendly Stage 2 path with CEL suppression options.',
  'Street Stage 2 DP',
  20,
  28,
  'tuner',
  'MOT Compliant',
  'Stage 1/2 ECU tune',
  ARRAY['n54', 'n55', 's55', 'b58', 's58'],
  'downpipe',
  NULL,
  NULL
),
(
  'uk-milltek-opfback',
  'OPF-Back Exhaust System',
  'Milltek Sport',
  'exhaust',
  1350.00,
  'Milltek Sport OPF-back system — retains the OPF/GPF, sharpens tone, mild flow gain. Popular on UK G-series cars.',
  'OPF stays, sound wakes up',
  8,
  10,
  'tuner',
  'MOT Compliant',
  NULL,
  ARRAY['b58', 's58', 's55'],
  'catback',
  '/audio/b58-milltek-revs.mp3',
  '/audio/b58-milltek-flyby.mp3'
),
(
  'uk-remus-valved-axleback',
  'Valved Axle-Back System',
  'Remus',
  'exhaust',
  1480.00,
  'Remus valved axle-back — OEM valve control compatibility, deeper tone, modest weight save.',
  'Valved street tone',
  5,
  6,
  'tuner',
  'MOT Compliant',
  NULL,
  ARRAY['n54', 'n55', 's55', 'b58', 's58'],
  'axleback',
  '/audio/b58-remus-revs.mp3',
  '/audio/b58-remus-flyby.mp3'
),
(
  'uk-aa-equal-length-midpipe',
  'Equal Length Midpipe',
  'Active Autowerke',
  'exhaust',
  1200.00,
  'Active Autowerke equal-length midpipe — balances pulses on twin-turbo S55/S58 and cleans up the soundtrack. Often OPF-adjacent on G-cars.',
  'Equal-length tone',
  10,
  12,
  'tuner',
  'OPF Bypass Required',
  'Stage 1/2 ECU tune',
  ARRAY['s55', 's58', 'b58'],
  'midpipe',
  NULL,
  NULL
),
(
  'uk-cobra-sport-decat',
  'Decat Exhaust Section',
  'Cobra Sport',
  'exhaust',
  890.00,
  'Cobra Sport UK decat / resonated delete section — loud, free-flowing. Track / off-road use only on UK roads.',
  'UK decat section',
  15,
  18,
  'estimated',
  'Track / Off-Road Only',
  NULL,
  ARRAY['n54', 'n55', 's55', 'b58', 's58'],
  'decat-section',
  NULL,
  NULL
),
(
  'uk-opf-bypass-midpipe',
  'OPF / GPF Bypass Mid-Pipe',
  'Milltek Sport',
  'exhaust',
  780.00,
  'OPF/GPF bypass mid section for G-series cars. Needs a supporting ECU tune — expect MOT scrutiny.',
  'OPF delete section',
  12,
  16,
  'estimated',
  'OPF Bypass Required',
  'Stage 1/2 ECU tune',
  ARRAY['b58', 's58'],
  'opf-section',
  NULL,
  NULL
),

-- ═══════════════════════════════════════════════════════════════
-- 4. TURBOS & FUELING (BIG POWER)
-- ═══════════════════════════════════════════════════════════════
(
  'uk-pure800-hybrid-turbo',
  'Pure800 Cast Hybrid Turbocharger',
  'Pure Turbos',
  'forced-induction',
  2650.00,
  'Pure800 cast hybrid — big-power step for BMW turbos. Needs upgraded HPFP and a high-flow downpipe.',
  '+180 HP territory',
  180,
  220,
  'tuner',
  'Track / Off-Road Only',
  'Upgraded Fuel Pump & Downpipe',
  ARRAY['n54', 'n55', 's55', 'b58', 's58'],
  'turbo-upgrade',
  NULL,
  NULL
),
(
  'uk-pure750-hybrid-b58',
  'Pure750 Hybrid Turbo (B58)',
  'Pure Turbos',
  'forced-induction',
  2200.00,
  'Pure750 hybrid for B58 — strong street/track step below Pure800. Pair with Stage 2+ fueling and DP.',
  'B58 big-turbo sweet spot',
  140,
  170,
  'tuner',
  'Track / Off-Road Only',
  'Upgraded Fuel Pump & Downpipe',
  ARRAY['b58'],
  'turbo-upgrade',
  NULL,
  NULL
),
(
  'uk-dorch-stage2-hpfp',
  'Stage 2 HPFP',
  'Dorch Engineering',
  'fueling',
  1250.00,
  'Dorch Engineering Stage 2 HPFP — prerequisite for Stage 2+ / Flex Fuel on BMW turbo platforms.',
  'Fuel for Stage 2+',
  0,
  NULL,
  'tuner',
  'MOT Compliant',
  'Stage 2 ECU / Flex Fuel',
  ARRAY['n54', 'n55', 's55', 'b58', 's58'],
  'hpfp',
  NULL,
  NULL
),
(
  'uk-spool-fx150-hpfp',
  'FX-150 HPFP',
  'Spool Performance',
  'fueling',
  1100.00,
  'Spool Performance FX-150 high-pressure fuel pump — supports E85 and hybrid turbo fuel demand on B58/S58/S55.',
  'FX-150 fuel headroom',
  0,
  NULL,
  'tuner',
  'MOT Compliant',
  'Stage 2 ECU / Flex Fuel',
  ARRAY['n55', 's55', 'b58', 's58'],
  'hpfp',
  NULL,
  NULL
),

-- ═══════════════════════════════════════════════════════════════
-- 5. SUSPENSION & HANDLING
-- ═══════════════════════════════════════════════════════════════
(
  'uk-kw-v3-inox',
  'V3 Inox-Line Coilovers',
  'KW',
  'suspension',
  2150.00,
  'KW V3 Inox-Line — separate rebound and compression adjustment, stainless bodies, UK-friendly ride heights.',
  'Track-day damping',
  0,
  NULL,
  'oem',
  'MOT Compliant',
  NULL,
  ARRAY['n54', 'n55', 's55', 'b58', 's58'],
  'coilovers',
  NULL,
  NULL
),
(
  'uk-eibach-prokit-30',
  'Pro-Kit Lowering Springs',
  'Eibach',
  'suspension',
  260.00,
  'Eibach Pro-Kit lowering springs (~25–35 mm depending on chassis) — OEM damper friendly street stance.',
  'Clean street drop',
  0,
  NULL,
  'oem',
  'MOT Compliant',
  NULL,
  ARRAY['n54', 'n55', 's55', 'b58', 's58'],
  'springs',
  NULL,
  NULL
),
(
  'uk-hr-supersport-springs',
  'Super Sport Springs',
  'H&R',
  'suspension',
  240.00,
  'H&R Super Sport springs — progressive rate, popular UK drop that keeps OEM dampers happy.',
  'Progressive street springs',
  0,
  NULL,
  'oem',
  'MOT Compliant',
  NULL,
  ARRAY['n54', 'n55', 's55', 'b58', 's58'],
  'springs',
  NULL,
  NULL
),
(
  'uk-bimecc-spacers-12-15',
  'Hubcentric Wheel Spacers 12mm/15mm Kit',
  'Bimecc',
  'wheels',
  120.00,
  'Bimecc UK hubcentric spacer kit (12 mm front / 15 mm rear typical set) — bolt-on stance and track width. TUV-style hubcentric design.',
  'Hubcentric UK spacers',
  0,
  NULL,
  'oem',
  'MOT Compliant',
  NULL,
  ARRAY['n54', 'n55', 's55', 'b58', 's58'],
  'spacers',
  NULL,
  NULL
),

-- ═══════════════════════════════════════════════════════════════
-- BONUS UK STAPLES (to clear 30+ SKUs with real shelf presence)
-- ═══════════════════════════════════════════════════════════════
(
  'uk-csf-b58-chargecooler',
  'B58 Chargecooler Upgrade',
  'CSF',
  'forced-induction',
  1595.00,
  'CSF high-capacity B58 chargecooler — fights heat soak on Stage 2 / hybrid builds.',
  'Heat-soak insurance',
  12,
  15,
  'tuner',
  'MOT Compliant',
  NULL,
  ARRAY['b58'],
  'chargecooler',
  NULL,
  NULL
),
(
  'uk-wagner-comp-ic',
  'Competition Intercooler',
  'Wagner Tuning',
  'forced-induction',
  895.00,
  'Wagner Tuning Competition FMIC — dense core, strong UK Stage 2 staple on N55/B58 F-series.',
  'Competition FMIC',
  10,
  12,
  'tuner',
  'MOT Compliant',
  NULL,
  ARRAY['n55', 'b58', 'n54'],
  'intercooler',
  NULL,
  NULL
),
(
  'uk-do88-s55-chargecooler',
  'S55 Chargecooler Performance Pack',
  'do88',
  'forced-induction',
  1890.00,
  'do88 S55 chargecooler pack — big heat capacity for F80/F82/F87 Competition Stage 2.',
  'S55 heat control',
  14,
  18,
  'tuner',
  'MOT Compliant',
  NULL,
  ARRAY['s55'],
  'chargecooler',
  NULL,
  NULL
),
(
  'uk-powerflex-rear-subframe',
  'Rear Subframe Bushing Kit',
  'Powerflex',
  'suspension',
  285.00,
  'Powerflex polyurethane rear subframe bushings — sharper turn-in, common UK handling upgrade.',
  'Tighter rear end',
  0,
  NULL,
  'estimated',
  'MOT Compliant',
  NULL,
  ARRAY['n54', 'n55', 's55', 'b58', 's58'],
  'bushings',
  NULL,
  NULL
),
(
  'uk-ngk-r7437-6',
  'Heat Range 9 Spark Plug Set (×6)',
  'NGK',
  'fueling',
  95.00,
  'NGK R7437-9 (or equiv. heat-9) plug set for boosted BMW straight-sixes — Stage 1/2 essential.',
  'Colder plugs for boost',
  0,
  NULL,
  'oem',
  'MOT Compliant',
  NULL,
  ARRAY['n54', 'n55', 's55', 'b58', 's58'],
  'spark-plugs',
  NULL,
  NULL
),
(
  'uk-bm3-stage-license',
  'Stage 1 & 2 License Bundle',
  'bootmod3',
  'ecu',
  495.00,
  'bootmod3 combined Stage 1 & 2 OTS license SKU as commonly sold by UK retailers — maps for supported BMW turbos.',
  'OTS Stage 1–2 maps',
  60,
  80,
  'tuner',
  'MOT Compliant',
  'High-Flow Downpipe for Stage 2',
  ARRAY['n54', 'n55', 's55', 'b58', 's58'],
  'ecu-tune',
  NULL,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  name              = EXCLUDED.name,
  brand             = EXCLUDED.brand,
  category          = EXCLUDED.category,
  price_gbp         = EXCLUDED.price_gbp,
  description       = EXCLUDED.description,
  claim             = EXCLUDED.claim,
  hp_gain           = EXCLUDED.hp_gain,
  torque_nm_gain    = EXCLUDED.torque_nm_gain,
  figures_source    = EXCLUDED.figures_source,
  uk_mot_status     = EXCLUDED.uk_mot_status,
  prerequisite_sku  = EXCLUDED.prerequisite_sku,
  compatible_tags   = EXCLUDED.compatible_tags,
  conflict_group    = EXCLUDED.conflict_group,
  audio_revs_url    = EXCLUDED.audio_revs_url,
  audio_flyby_url   = EXCLUDED.audio_flyby_url;
